# Generated by Django 4.2.11 on 2024-03-14 10:49

from django.db import migrations, models
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):
    dependencies = [
        ("river", "0002_alter_onapprovedhook_callback_function_and_more"),
        ("demo_test", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("order", models.IntegerField()),
                (
                    "my_state_field",
                    river.models.fields.state.StateField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="river.state",
                    ),
                ),
            ],
        ),
    ]
